name: "Custom Composite Action"
description: "Akcija za automatsko preuzimanje koda i izvršavanje skripte"
author: "Marko"

inputs:
  message:
    description: "Poruka za ispisivanje"
    required: true

outputs:
  result:
    description: "Rezultat izvršenja skripte"
    value: ${{ steps.run-script.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Checkout koda
      uses: actions/checkout@v4

    - name: Pokreni skriptu
      id: run-script
      run: |
        chmod +x ./entrypoint.sh
        ./entrypoint.sh "${{ inputs.message }}"
      shell: bash

    - name: Postavi izlaznu vrednost
      run: echo "result=Script executed successfully" >> $GITHUB_OUTPUT
      shell: bash

branding:
  icon: "smile"
  color: "blue"
