name: Testiranje composite akcije

on: [push]

jobs:
  run-composite-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repozitorijuma
        uses: actions/checkout@v4

      - name: Pokreni composite akciju
        uses: ./akcija
        with:
          message: "Pozdrav od GitHub Actions"
      
      - name: Prikaz izlaza
        run: echo "Rezultat akcije: ${{ steps.run-script.outputs.result }}"
